[dependencies]
fitsio = '0.14.1'
image = '0.21.0'
imageproc = '0.18.0'
ndarray = '0.12.1'
num-traits = '0.2.6'
statistical = '1.0.0'

[dependencies.fitsimg]
path = '../rust_fitsimg'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
edition = '2018'
name = 'seekrfi'
version = '0.1.0'
