[dependencies]
fitsio = '0.15.0'
image = '0.22.3'
imageproc = '0.19.2'
ndarray = '0.13.0'
num-traits = '0.2.9'
statistical = '1.0.0'

[dependencies.fitsimg]
path = '../rust_fitsimg'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
edition = '2018'
name = 'seekrfi'
version = '0.1.0'
